### ISSUE TITLE
Ensuring Inclusivity

### ISSUE THREAD

**Issue by remixz** [hoodiehq/editorial#15]
In the #editorial Slack channel ([which you should join](http://hood.ie/chat), if you haven't already!), @Charlotteis brought up the point of making sure we hear from everybody in the community who has interest in this project.

> charlotteis [11:53 UTC-8] 
Question: how many people should review submission of processes before we merge them?

> charlotteis ​[11:54 UTC-8] 
I want to make sure the majority of happy with process before we commit them to stone (merge a PR)

> charlotteis ​[11:55 UTC-8] 
Not a criticism of the good work that has been happening whilst Ive been unable to help, but more of a query!

> charlotteis ​[11:56 UTC-8] 
And what do we do if there are fundamental disagreements in processes that are merged without group consensus.

> zach [11:57 UTC-8] 
@charlotteis: we should have at least a couple people give a :+1:, but for at least how i see it, i don't think merging a process means it's set in stone. processes should always evolve as a project goes on, so i personally feel we shouldn't be too cautious to merge quickly, and then iterate over time

> charlotteis [11:57 UTC-8] 
Again NOT a criticism. Ive just spent a long day of thinking about processes and I am trying to pre empt events that will eventually happen in the future.

> charlotteis ​[11:58 UTC-8] 
So in my ezperience, particularly with underrepresented folk, they might not feel comfortable/capable of challenging a process.

> charlotteis ​[11:58 UTC-8] 
Just thinking out loud :)

I want to start with @Charlotteis' point of making sure we get enough feedback on our processes. I think that as developers, we have a bit of an itch to merge pull requests as soon as possible. :laughing: For this kind of project, I think that leaving pull requests for process documentation open for a little while is fine. In the Slack channel, a 72 hour time period for has been suggested. I'm :+1: on this. The few pull requests that have been merged quickly so far are good, since it's given us a base to work off of. We're now able to at least get things started for publishing a post, as seen on GH-14. 

Next, on the point of disagreements: They'll happen! We should be prepared for them. Not only that, we should _welcome_ them. Being able to be candid is important for the best ideas to come out. However, I definitely recognize that bringing up a disagreement in an open environment like ours, especially when there may be a multitude of people who disagree with a disagreement, can be very scary. No one wants feelings to be hurt, and we definitely don't want to drive someone away because of criticism. As well, if someone is contributing that you may look up to, it can be hard to give criticism, since you don't want to offend them, you might feel like an imposter, of sorts, telling them something is wrong, or you just don't want to risk publicly feeling embarrassed.

All of this comes from the stigma of failure being "bad", and that we should never fail. I think that as a project, and as a community, we should try to challenge that. If anything, we should encourage failing fast, and failing early. That way, by the time we ship something, we have something :sparkles: absolutely amazing :sparkles:.

I think we should come up with some mission statements for this project, that celebrate the creative spirit we aspire to have, and that inspire people to get involved. They can be similar to [the statements Hoodie already has](http://hood.ie/about/). I'll likely write up a couple at some point, but I really want to make sure everyone has the chance to suggest what we're trying to foster in this community, so that we're actively working together. The more we work together, the more trust we build between each other, which will lead to more openness and candor, which will create super awesome products!!

Finally, on the point of including people from underrepresented groups. I mentioned this in the Slack channel as well, but I really think we're on the right path by working transparently as we have so far. Overall, this is something I really feel we can, and we should, do right. I want to leave it to others to give their thoughts on this matter, since I'm not really affected in the same way as some people, and won't have the perspective others will. All I want to make sure is that we feel comfortable talking about this. :smile:

As always, I welcome everyone's feedback and comments. :tada: 

---

P.S.

I've been writing a lot of process stuff for this team, as I'm really excited about its possibilities. I hope that no one feels I've dominated any conversations so far. I promise you: it's just excitement, and a motivation to get this project to its full potential! Whenever I ask for feedback, I truly mean it, and I'm always happy about everything everyone has to say. My goal for now with my participation in this project is to get the ball rolling, so that soon enough, it's a bit less of what we're going to do, and a bit more of what we are doing. :wink:

**Comment by schisepo** [comment]
👍

**Comment by bnb** [comment]
I want to preface this saying that I have a very subjective viewpoint about how community-managed repositories should work. This is due to my involvement in the development of the Node.js/io.js Website and Evangelism Working Groups. They follow an ideology that has struck a nerve with me, and I think that community-managed projects and take a lot from them.

Okay, so how do the majority of Node WGs handle contributions? It's done by trust. When people demonstrate that they are positive contributors to the projects, they are added as a contributor to the respective team on the GitHub org and are given commit access.

You would think this would descend into chaos, right? Hell. No. Remarkably, all the people who have been given contributor status and commit access have been amazingly positive and professional. It ended up being an unintended social experiment that resulted in showing how freaking awesome the OSS, JS, and Node communities are.

How does this tie in with the editorial initiative Hoodie has? One of the core tenets of the governance model, which defines the contributor concept defined described above, is that the groups are _consensus seeking_. 

They do not rely on full approval of all parties represented. As almost anyone in a community that makes decisions can tell you, if you need full approval for every matter, nothing will ever happen, interest will be dropped, and the community will dissolve.

What the consensus-seeking model does is finds what the majority of the group that can be represented at present thinks is best. Compromises can be almost always be made if there is a disagreement. When there are two opposing perspectives, it is up to the majority of the group that is present to make a concise decision, or table the issue to take into consideration variables that will happen in the near future that will affect the decision.

The consensus-seeking model is good for directional choices that steer the group's development. However, there are always going to be those little contributions like typo fixes and non-major additions that would be ridiculous to wait until a meeting to discuss and merge. In this case, those marked as contributors to the project will review these changes. If there is nothing that needs to be taken into consideration, contributors will drop a ’+1’ or ’LGTM’. If there is an issue with the contribution, it will be raised by a contributor or anyone else that may want to review commits. Depending on the severity and scope of a change, a contribution may be accepted by a contributor. In cases such as changing a link or fixing a typo, a contribution may be accepted after there is two +1s. Other times, when there is a major contribution, the contributors may want to either discuss the topic in a meeting, or ask a project leader for guidance. For everything in-between, the contributors are able to gauge the brevity of the topic and make appropriate choices. Again, amazingly, when contributors are added based on positive work, they continue to produce more positive work for the community.

If you have any questions, feel free to ask. Also, apologies if there are misspelled words - my computer is unusable, so I've been on mobile.

**Comment by Charlotteis** [comment]
Good comments here. Consensus is great. The reason I posed the questions was because I didn't feel we had sought a consensus when we merged some of our processes. I like the 72-hour window as it gives everyone 3 days to raise any issues they have with new process proposals. :)

**Comment by renrutnnej** [comment]
I also like the 72 hour window, that accounts for what I believe to be an appropriate window across timezones. 

I’m also a big :+1: on consensus, thank you for your thoughts on that @bnb :pray: 

As far as creating separate mission statements for the editorial team, I’m curious if we need to make sure they are informed by the [initiatives found](http://hood.ie/initiatives/) in the [contribution guide](https://github.com/hoodiehq/editorial/blob/master/CONTRIBUTING.md). I’m reviewing them and the initiatives appear to be mostly directive in terms of the focus of the overall project.

I’m anti-mission statement having worked under so many empty ones so this issue caught my attention (although I clearly understand the good intention behind it @remixz :relaxed:). I favor values-driven communities/companies instead so I would push for articulating that over trying to determine mission statements (which can be too broad/general). 

Also in terms of handling disagreements/conflicts [nonviolent communication](http://www.nonviolentcommunication.com/aboutnvc/4partprocess.htm) has a great process that I know has been used in the Node community as well. 

All of these discussions have been so awesome, thank you all :sparkles:

**Comment by bnb** [comment]
@renrutnnej: Thanks for the comments! I do have a question, though. 

You say you're anti-mission statement, and prefer value based community instead. You mentioned that we should find a way to articulate those values - how is articulating values different than a mission statement?

**Comment by renrutnnej** [comment]
@bnb Great question! 

At my last company we used a differentiation that has become important to me, so I'm sure that's where the strong opinion comes from :relaxed: 

I see a mission statement being more reflective of the product/what we do and values statement being centered around the people/who we are. 

It could one hundred percent be a silly semantics argument on my part, but my experience within the hoodie community so far seems more about the people than anything else :sunglasses:

**Comment by skeskali** [comment]
I'm a librarian who works at a library that is big on mission, vision, and values statement. Mission statement vs. values statement isn't a semantic difference. A mission statement talks about what you're going to do, and should be the goal that drives the organization. The values statement talks about your organization's/community'sservice ethic. These things can overlap, and one should definitely inform the other but the statements themselves work best when they're distinct.

**Comment by schisepo** [comment]
@skeskali would what's in the readme.md qualify as our mission and vision? It outlines what we're going to do :smile: Our Coc outlines values I think

**Comment by bnb** [comment]
@schisepo CoCs shouldn't reflect values, as I understand them. CoCs are the baseline for conduct within a group, description describe the things that should and shouldn't be done on a behavioural level. Is a CoC more than that?

**Comment by skeskali** [comment]
That's my understanding of a C0C too, @bnb. Mission statements are best and more impactful when they're brief, or so said the consultant we worked with when we wrote ours.

**Comment by bnb** [comment]
@skeskali I would definitely agree that mission statements are more impactful when they're brief. In many cases, the heading on the index page of a software project should be the most distilled summary of the mission statement. 

This is actually something that Hoodie has suffered with for a while - when I first saw/heard about it, I took a look at the front page and withdrew because there wasn't a clear message that said what Hoodie is or does.

So, if we can come up with a mission statement for Hoodie, we'll be a step up from where we are now. If we can get a set of values (in what format would we share values), we'd be even higher.

**Comment by Charlotteis** [comment]
Seems like this discussion ended, do we want to create an issue specific to creating a mission statement? Do we need one? Seems like there is still some confusion. Happy to help unconfuse if I can!

**Comment by bnb** [comment]
What I think the decided course of action is:
* Create a CoC
* Create a Mission Statement
* Documentation in the repo (`CODEOFCONDUCT.md` and `MISSION.md`?)

**Comment by Charlotteis** [comment]
Hoodie does have a CoC already, so we should be good on that front.

**Comment by renrutnnej** [comment]
I just added a draft of a Mission Statement to the README via this PR (https://github.com/hoodiehq/editorial/pull/56) and would love feedback/reviews!

**Comment by renrutnnej** [comment]
Published a Mission Statement in the README today so I'm closing this now since there wasn't any other discussion.

**Comment by skeskali** [comment]
I'm sorry I missed this. I was in hospital for a few days and only just saw it.

**Comment by Charlotteis** [comment]
@skeskali Absolutely no need for apologies. Sorry to hear you were in the hospital, I hope you're doing ok!
