### ISSUE TITLE
Define a formal method in which contributors are added to the Editorial team

### ISSUE THREAD

**Issue by bnb** [hoodiehq/editorial#24]
I updated the `team-roles.md` file with descriptions in https://github.com/hoodiehq/editorial/pull/23. In addition to adding the descriptions, I think we need to define a formal process in which contributors are added to the Editorials team. 

Having this early on makes the transition from one (or few) contributor to many slide through with much less friction than when it is developed later.

Tasks for getting this done:

- [x] Separate file or put in `team-roles.md`?
- [x] Different path to contributor for each of the defined roles in `team-roles.md` or a unified path?
- [x] ~~Define what `active` and `contribution` mean.~~
- [ ] Link to CoC, `CONTRIBUTING.md`, and anything else?
- [ ] {{other points?}}

**Comment by remixz** [comment]
:+1: 

For code repositories, some that I've been involved with use a system of once a person has made a decently-sized contribution (i.e. more than just fixing a typo in a README), they're added as a contributor to the repository. They're expected to follow the contribution guidelines, which is usually just things like don't force push a branch, etc. There's no expectation of how active they are, so they can be as active as they want. People are usually more active when they're added a contributor, though, since they feel like they're recognized for their work. When people feel recognized and appreciated for what they do, they generally want to continue to do that thing. Positive reinforcement! :smile: 

I think we can adapt this model for this team. If someone wants to be an editor, let's say, then once they've contributed to editing an article, and that article was published with their editorial insight, then that person is made a contributor. If they abuse the contributor power somehow, then they'd be removed. However, the more likely outcome is that they'd feel recognized and appreciated for their work, and would want to contribute again. Maybe they'd help get involved in other ways as well! In my experience, this model has a really positive outcome. I've personally never seen anyone abuse their power when added as a contributor, either. Most people tend to judge pretty well where their boundaries are in a project, and I don't see why it wouldn't be the same for this team.

**Comment by bnb** [comment]
@remixz :+1: to everything you said. I've also **never** seen someone who is added as a contributor do anything that negativity affects the community or the content they are responsible for. 

I know that one issue that some people have with this concept is the too many cooks situation. However, I've never seen a more productive, friendly community than the Node (io.js) projects with their unlimited contributor rosters. Once people are marked as a contributor, they are, as you said, more attached to the community and are more likely to stay longer or come back.

**Comment by schisepo** [comment]
@bnb the call for contributors welcomed even people who are only able to contribute an hour a week. I think if we are too strict on marking contributors, we might defeat the purpose of a safe, non-demanding, load shared open source project which is part of the appeal to me.

Our process needs to cater for once-off contributors as well. I loved how credit was given to those involved in editing the minute.io article that was put up on the blog. Contributions should be recognised atomically.

**Comment by bnb** [comment]
@schisepo Fair point. I struck the point about active/contributor.

**Comment by bnb** [comment]
Is there a CoC for this repo, or a blanket one for all Hoodie projects? If not, the CONTRIBUTING.md file is linked in the README.md file, meaning that item can be struck as well.

**Comment by Charlotteis** [comment]
http://hood.ie/code-of-conduct/

**Comment by renrutnnej** [comment]
We're going to follow the contributing guidelines of the overall project, so no formal process is necessary.
