### ISSUE TITLE
Meet the Hoodie - @charlotteis

### ISSUE THREAD

**Issue by schisepo** [hoodiehq/editorial#40]
Hi @Charlotteis  :smiley: :wave: 

We'd like to feature you in our "Meet the Hoodies" series. We're working on this series to get the editorial process right and to introduce/ re-introduce the amazing people behind Hoodie. Kindly respond to the questions below and submit a quirky photo to go with the final blog post:

1. What's your favorite animal?

2. What's your role / what have you contributed to Hoodie?

3. What's your favorite use of Hoodie in the wild?

4. What in your opinion makes the Hoodie project unique and interesting?

5. What advice do you have for aspiring Hoodie contributors?

Issue #14 

@skeskali @remixz @bnb @renrutnnej would any of you be available to test drive the blog process guided by this doc :point_right: [Our blog process] (https://github.com/hoodiehq/editorial/documents/blog-process.md) and this document :point_right: [Submitting a PR to the Hood.ie blog WIP] (https://github.com/hoodiehq/editorial/blob/guide-pull-request/documents/submitting-a-pr-to-hoodie.md)

**Comment by Charlotteis** [comment]
Hello @schisepo, thanks for setting this up!

**I have answered most of these but please consider this a draft, a lot of it is clumsily worded and I haven't answered the final question and would like to think on it some more**.

**What's your favourite animal**

Growing up I had many favourite animals, including the White Bengal Tiger. Now, I think I've settled on the Fox. They used to hang out underneath my bedroom window in London at 2am every night, and I think they're very beautiful creatures! If I had to own an animal, it would probably be a Cat because I don't think I could keep a Fox. Cats are cool because they seem to have a much more introverted and independent personality than other animals (like some Dogs), which I have too.

**What's your role / what have you contributed to Hoodie?**

I came to Hoodie in May 2015. One day I was bored and someone on Twitter (probably @janl) mentioned Hoodie. I checked it out and noticed some spelling mistakes on the main website so I started firing off a flurry of Pull Requests and they were all accepted! I was also learning more about Accessibility at the time (and still am) so I started PR'ing accessibility improvements to various repositories.

Now, I'm fully employed and I don't get a lot of time to work on things. So my contributions are mainly talking with people in Slack and listening to peoples ideas (also known as []rubber ducking](link to rubber ducking), it is a very important part of teamwork). Recently I've helped start the Hoodie Editorial team which is going really well and they are producing awesome blog posts and works like this very one I am writing in (meta!). 

In 2016 I want to get better at JavaScript and use the Hoodie internals as a way of learning, so hopefully I'll start to contribute features that Hoodie users will love!

**What's your favourite use of Hoodie in the wild?**

Reading the [minutes.io case study](http://hood.ie/blog/minutes-offline-case-study.html) written by [Alex], was fascinating, so that's probably my favourite use. However this is totally considered cheating as minutes.io was where Hoodie itself originated so it is actually the first use of Hoodie in the wild!

In general, all uses of Hoodie are my favourite (yes, I know, cheating again). It's a joy to see people come to talk us in [Slack](https://hood.ie/chat) and share their prototypes and applications with us.

**What in your opinion makes the Hoodie project unique and interesting?**

The community. I'm happy to say this, and have said this to other Hoodie members in the past; but Hoodie (the thing you use to build awesome applications) is something I often do not pay much attention to. Ninety nine percent of my focus is on the people who make that project.

Since I have been a part of Hoodie I have seen it go through a lot of evolution. We've shifted our focus from "code code code" to "how can we help others to code with us?". We've hosted some fantastic people from the Rails Girls Summer of Code, we regularly discuss inclusivity and accessibility for every part of the Hoodie experience and we're just now starting to make events for new contributors to Open Source to come and join us for a day and get started with making their first PR.

There are many fantastic communities out there, but I feel that Hoodie is a unique example of a well established project where some their best teachings are people-based rather than code-based. We obviously have a long way to go and will never be finished, but it is refreshing to be a part of this positive attitude within Open Source.

**What advice do you have for aspiring Hoodie contributors?**

Let me think on this some more!

**Comment by Charlotteis** [comment]
I think I also need to make everything short :see_no_evil:

**Comment by gr2m** [comment]
this is very, very lovely, @Charlotteis. Reading this totally made my day <3

**Comment by Charlotteis** [comment]
:sparkling_heart:

**Comment by janl** [comment]
This is all great, I filled out two empty links, hope you don’t mind :)

@Charlotteis whenever you are up for answering the last question, after that it’s ready to go IMHO :)

**Comment by Charlotteis** [comment]
Sure thing, I'm so swamped with life and holidays and am back to work on Tuesday. However if I get some time tomorrow I will tidy this up. Else, I will for sure carve some time out another day this week.

**Comment by Charlotteis** [comment]
I have answered the final question. I just need to go through and correct grammar and spelling. Appreciate anyone who has the time to look at this :)

**Comment by schisepo** [comment]
Taking a look😊

**Comment by Charlotteis** [comment]
I also made a .gif as you wanted a quirky image :D

**Comment by janl** [comment]
@Charlotteis looks great! :)

I changed “Node.JS” to “Node.js”, hope you don’t mind.

**Comment by schisepo** [comment]
I'd create a PR for the .md file from which we can make further edits but I
can't access the .md for the comment 😯

**Comment by Charlotteis** [comment]
> I changed “Node.JS” to “Node.js”, hope you don’t mind.

Our styleguide says to say "Node.JS". Which is the right one?
https://github.com/hoodiehq/editorial/wiki/Glossary-of-common-terms#n

Here you go @schisepo -> https://gist.githubusercontent.com/Charlotteis/7217c50535460435c4ee/raw/0dbd997b9bb6b82f50f9820233e8d9f4937f2978/meetthehooides.md

**Comment by Charlotteis** [comment]
^ @janl

**Comment by renrutnnej** [comment]
@Charlotteis @janl feel free to update the styleguide! I used the phrases I found from copy on all of the Hoodie sites as a reference.

**Comment by schisepo** [comment]
@everyone, @Charlotteis's "Meet the Hoodie" blog post is available for editorial review here -> [PR for Charlotte's article] (https://github.com/hoodiehq/editorial/pull/47). We have 72 hours :smiley:

**Comment by janl** [comment]
fixed the style guide :P

**Comment by Charlotteis** [comment]
Thanks everyone! :)

**Comment by gr2m** [comment]
Just one thought: can we put it online on Jan 5th or so? I’d be a great article to kick off the new Hoodie year, and if we launch it on Jan 1st probably many people won’t see it?

**Comment by janl** [comment]
I definitely suggest we do it Jan 5!

The 72 hours is for everyone giving feedback, not when it (necessarily) goes live.

**Comment by Charlotteis** [comment]
Agreement :)

**Comment by janl** [comment]
And we’re live! https://github.com/hoodiehq/hood.ie/pull/221 \o/

**Comment by Charlotteis** [comment]
:+1:
