### ISSUE TITLE
Wikipedia

### ISSUE THREAD

**Issue by o4tuna** [hoodiehq/editorial#57]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

How to add/edit entries for [Wikipedia](https://en.wikipedia.org/wiki/Main_Page), as noted here [Your first article](https://en.wikipedia.org/wiki/Wikipedia:Your_first_article) and [Article development](https://en.wikipedia.org/wiki/Wikipedia:Article_development).
### 🐞 The Issue

There's no Wikipedia entry for Hoodie.
### :dart: The goal

Create an entry for Hoodie! 🐶 
### :clipboard: Step by Step
- [ ] **claim this issue**  
  comment below. Once claimed we add you as contributor to this repository, so we can assign you to the ticket and you can start checking off the checkboxes below as you progress. We will also replace the `ready` label with `in progress`.
- [ ] Familiarize yourself with the Wikipedia publication process.
- [ ] Write a draft of an article for Hoodie 
- [ ] Get feedback on the article from the editorial team 
- [ ] Submit to Wikipedia 
- [ ] **Done** :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by summerspirit** [comment]
Suggestions for articles to model after?
[Puppet](https://en.wikipedia.org/wiki/Puppet_(software))
[Rails](https://en.wikipedia.org/wiki/Ruby_on_Rails)

Or do we want to go some other direction for it?
I'm just posting possible models to follow because Wikipedia gave me a warning that it should be an encyclopedia entry, not a sales pitch. I hadn't even typed anything! lol

**Comment by renrutnnej** [comment]
Are you volunteering to take this on @summerspirit?

**Comment by summerspirit** [comment]
@renrutnnej Sure! Assigned it to myself.
I'll submit it here like a blog post for review though, in a Google docs link, before I post it live.

**Comment by renrutnnej** [comment]
Hi @summerspirit just checking in on this to see how you're doing and if you need any assistance :relaxed:

**Comment by fozy81** [comment]
Hi, my name's Tim . I hope @summerspirit doesn't mind  but I've put together a [draft wikipedia entry here](https://en.wikipedia.org/wiki/User:Fozy81/sandbox). It's in my sandbox area on wikipedia user page, hopefully other people can log in to edit/talk about it there before posting. Or discuss on this thread/issue. 

I can't seem to  add images until the article is formally added to wikipedia. But can add Hoodie logo and perhaps a diagram of the app/pouchdb/counchdb interaction in future. 

It needs a few more references...

I've recently been trying out Hoodie and really like the idea. I'm not experienced at web development and using Hoodie is my first real attempt at javascript/web framework.  So I thought I could help out in a non-technical way.  Although the article is quite techie itself! and I may have not explained Hoodie correctly. Please edit mistakes...

**Comment by gr2m** [comment]
Thanks @fozy81 👍 I’m mostly off myself vacationing and working on other parts of Hoodie, but I’ll try to review it over the next week.

**Comment by janl** [comment]
Again, this is great, thank you! <3

@fozy81 I’ve added a few more references and cleaned up the style a little bit.

@gr2m Can you look at the example code section, it should show what we have for Camp, not the old API.

After that, I’m +1 submitting this.

**Comment by gr2m** [comment]
hey I had a quick first look at it and I think it’s a fantastic start :thumbsup: thanks so much :bouquet:

Just one question that I have is why you list "Firebase" in the see also section? You don’t mention it anywhere else in the content so I don’t know what to make of it?

Something nice to do before we publish it would be to publish the docs for new Hoodie. When other Wikipedia authors will review it they might get confused as the current docs reference the current Hoodie which is no longer maintained. 

If you could have a look at https://github.com/hoodiehq/discussion/issues/109 and the preview of the new docs at http://hoodie-test.readthedocs.io/, that’d be great. 

@janl if you could give your +1 on this, I would like to go ahead with a pull request to the `hoodie` repository, and would suggest to point `docs.hood.ie` to the new documentation.

**Comment by fozy81** [comment]
Hi @gr2m, my thinking was to list other similar solutions to offline first apps solutions e.g. firebase. Perhaps best to leave out of this article, there's probably a case for 'nobackend' or 'offline first' standalone articles to list similar solutions e.g. https://wq.io/wq.app or pure local storage / html 5 . Although hoodie is quite unique, I still wanted to appear unbiased and point the reader towards other similar projects etc. I'll perhaps add something to the talk page to ask how best to group/categorise/mention similar projects in this emerging field.

**Comment by fozy81** [comment]
@janl  @gr2m  thanks for the input and updates - it's starting to take shape. If you can update the code example / docs when ready. I'll add some image files when it goes 'live'.

**Comment by gr2m** [comment]
Thanks for waiting! @janl will update the DNS so that http://docs.hood.ie/ points to our new documentation at hoodie.readthedocs.io and then I think we are good to go :) 

I don’t really know how things go about adding a new article to Wikipedia, but if there is anything we can help with, please let us know, we are here to help. Thanks again for your great efforts, much appreciated!

**Comment by fozy81** [comment]
It's [alive!](https://en.wikipedia.org/wiki/Hoodie_(software))  It's been 'reviewed' by wikipedia so it's 'official'.

Please edit/review further on wikipedia. 

I've added the hoodie logo and architecture diagram. But the hoodie logo is svg file and doesn't display well. **Are there any jpeg/png of the hoodie logo available?**

**Comment by gr2m** [comment]
Hey @fozy81 that is so cool, thanks so much! This must be one of the coolest contributions to the Hoodie community :) I’ve invited you to the Hoodie Contributors team, you should be able to accept at https://github.com/hoodiehq – welcome 🙌 

Are you on Twitter by chance? We love giving shout outs to our new contributors :) 
And congrats to your [first Open Source pull request](https://github.com/hoodiehq/hood.ie/pull/342), too 🎉

I had a quick look for the Hoodie logo but couldn’t find it :D It must be somewhere, I’ll make sure you get it

**Comment by fozy81** [comment]
Hi @gr2m, it's been fun and thanks for everyone's support. I'm @fozy81 on twitter. I'm hoping to help out more when I can. Starting to learn the basics of emberjs + hoodie. I got a background in using [R/shiny](http://shiny.rstudio.com/) web framework which is similar in the sense of super easy web apps. But client-side javascript is unavoidable when requiring more control/offline things to happen. Hoodie has lots of exciting possibilities.

**Comment by gr2m** [comment]
I'd be happy to help you find something interesting to work on! Our camp repository is a good place to look for things to work on: https://github.com/hoodiehq/camp/issues

Maybe a good way to start would be to build a simple app yourself, and maybe use Ember for the frontend? I’m interested in making the two work together well myself. We even started working on an adapter: https://github.com/hoodiehq/ember-hoodie. The work is somewhat stalled but definitely up for anyone to continue the work on it.

Thanks again for your help!

**Comment by gr2m** [comment]
hey @fozy81, the wikipedia article was flagged for deletion: https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Hoodie_(software). Could you give us some context on that, on the referencet to [WP:BOMBARDMENT](https://en.wikipedia.org/wiki/Wikipedia:BOMBARDMENT) and on what we can do to help prevent it from being deleted?

**Comment by fozy81** [comment]
Hey @gr2m, a couple of days ago the page was flagged for deletion because the subject was not deemed notable. In response, and in good faith, I added further references to show that it did have significance and secondary sources, following the wikipedia procedures, I then removed the proposal for deletion template. At this stage, I was hoping it was safe, but now it had been added to the 'Articles for deletion' list. My actions to improve references and show notability were termed 'Bombardment'. The decision to delete will be in about 7 days, in the meantime a community consensus must be reached. So people can add there comments to the discussion here:

 https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Hoodie_(software)
  
It may be of interest to read discussions of similar software articles prosposed for deletion here:
  
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Deletion_sorting/Software

I should say, I'm no expert on wikipedia - just done a very edits here and there - so don't know much about the rules and standards etc. Anyway, if enough people chime in with good reasoned augments, I'm sure a sensibly outcome will prevail.

**Comment by gr2m** [comment]
Thanks for your help and the clarification!

**Comment by fozy81** [comment]
Phew, article has been deemed notable so will be kept in Wikipedia! Congrats everyone, hoodie is staying in Wikipedia. I've been busy learning javascript, ember and hoodie but for now more skilled to help out with documentation/proof reading etc. Let me know if there's something I can help with @gr2m.

**Comment by gr2m** [comment]
@fozy81 thank you SO MUCH! 

I’m happy to help you interesting things of any kind for you to contribute. First thing that comes to mind is this issue here: https://github.com/hoodiehq/hoodie/issues/684 Feel free to comment on it and assign it to yourself. If you have any questions you can ask in the issue and we’ll help you out :)

**Comment by fozy81** [comment]
@gr2m that looks great, one line deploy! I'll have a read/watch and see if i can help update the docs.
